### ISSUE TITLE
User can view a list of notes.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/react-notes#1]
# Motivation

We want to see what we've learned

# Task implementation

- [x] Create a wire frame.
- [x] Add project scaffolding files (package.json, dependencies, scripts, etc.).
- [x] Create a notes SQL table and add dummy data.
- [x] Create an Express app with a route that serves a JSON list of notes.
- [x] Set up Express static middleware to serve HTML, CSS, and JS.
- [x] Define a NotesList React component that fetches and renders a list of notes.
- [x] Make the list look cool!

# Wireframe 

![screen shot 2017-08-01 at 10 26 00 am](https://user-images.githubusercontent.com/26865352/28838042-d8f16838-76a3-11e7-9876-d2310faf1359.png)
