### ISSUE TITLE
User can add a note.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/react-notes#3]
# Motivation 
We want to now be able to add notes.

# Task Implementation

- [x] Create a wire frame.
- [x] Add a route to the Express app that handles POST requests containing a new note.
- [x] Define a form component for accepting new notes.
- [x] Add handle form submissions by sending the new note data to the Express app.
- [x] Ensure that the new note is rendered in the list after it is saved.

# Wireframe

![screen shot 2017-08-01 at 2 22 05 pm](https://user-images.githubusercontent.com/26865352/28847635-d37d86cc-76c4-11e7-827c-21be47b62c8d.png)
