### ISSUE TITLE
User can delete a note.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/react-notes#5]
# Motivation

We want to be able to delete a note by its ID. 

# Task Implementation

- [x] Add an Express route for deleting a note by its id.
- [x] Enhance NotesList component to send DELETE request to the Express app when a note is clicked.
- [x] Ensure that the note is removed from the view when it has been successfully deleted.

# Wireframe
![screen shot 2017-08-02 at 12 57 23 pm](https://user-images.githubusercontent.com/26865352/28892244-28c366de-7782-11e7-827f-e921f18ad88f.png)
