### ISSUE TITLE
Add API Tests

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/react-notes#7]
# Motivation
We want to be able to test the program to make sure it works

# Task implementation
- [x] Import dependencies
- [x] Write some async tests
- [x] Verify that they work
- [x] Write some scripts to automate this behavior
