### ISSUE TITLE
Use environment variables

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/react-notes#9]
# Motivation

We want to be able to use a less pre-coded port

# Task Implementation
- [x] Get necessary dependencies
- [x] Assign port to variable
- [x] fix all the routes if they depend on a port
